### ISSUE TITLE
Add a little bit of Readme content

### ISSUE THREAD

**Issue by bocksskull** [bocksskull/localapp#1]

**Comment by jsjaskaran** [comment]
Hey @bocksskull I'd like to work on this.

**Comment by jsjaskaran** [comment]
Do you have any demo link for this? I mean is it hosted?

**Comment by bocksskull** [comment]
Yeah
http://parksapp.herokuapp.com

**Comment by jsjaskaran** [comment]
What things should I put in Readme

**Comment by bocksskull** [comment]
I mean its upto you but just a couple of lines and some routes info would be fine, gotta show it to someone.

**Comment by jsjaskaran** [comment]
Check it out, I just created a pull request. Is the readme enough?

**Comment by bocksskull** [comment]
Yes that would be enough. If any more things are needed, I'll just comment here.

Thanks

**Comment by bocksskull** [comment]
Hey @jsjaskaran Can you please do https://github.com/bocksskull/localapp/issues/3

**Comment by jsjaskaran** [comment]
Yeah sure why not. Mongodb is on mlab, right?

**Comment by bocksskull** [comment]
yes
